# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: ugy_webmin
    build: .
    command: flask run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/ugy_webmin.db
    volumes:
      - ./ugy_webmin:/code/ugy_webmin
      - ./db/:/db/
    ports:
      - "5000:5000"
